# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-HA
version:      0.99
version_from: lib/DBIx/HA.pm
installdirs:  site
requires:
    DBI:                           1.49
    Sys::SigAction:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
