#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-HA
version:      0.91
version_from: lib/DBIx/HA.pm
installdirs:  site
requires:
    Sys::SigAction:                0.04
    DBI:                           1.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
